# Generated by Django 6.0.3 on 2026-03-10 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='URL страницы (дублируется для удобства)', verbose_name='URL страницы')),
                ('organization_name', models.CharField(blank=True, help_text='Название организации', max_length=500, null=True, verbose_name='Название организации')),
                ('raw_html', models.TextField(blank=True, help_text='Сырой HTML страницы', null=True, verbose_name='Сырой HTML страницы')),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP статус код', null=True, verbose_name='HTTP статус код')),
                ('error_message', models.TextField(blank=True, help_text='Ошибка при загрузке', null=True, verbose_name='Ошибка при загрузке')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления', verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Собранные данные',
                'verbose_name_plural': 'Собранные данные',
                'db_table': 'crawled_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время запроса', verbose_name='Дата и время запроса')),
                ('results_count', models.IntegerField(default=0, help_text='Количество полученных результатов', verbose_name='Количество полученных результатов')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка')], help_text='Статус: success/error', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке', null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи', verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'Истории поиска',
                'db_table': 'search_history',
                'ordering': ['-search_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название темы', max_length=255, verbose_name='Название темы')),
                ('query_text', models.TextField(help_text='Текст поискового запроса', verbose_name='Текст поискового запроса')),
                ('region', models.CharField(blank=True, help_text='Регион поиска', max_length=100, null=True, verbose_name='Регион поиска')),
                ('pages_count', models.IntegerField(default=1, help_text='Количество страниц выдачи', verbose_name='Количество страниц выдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления', verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Тема поиска',
                'verbose_name_plural': 'Темы поиска',
                'db_table': 'search_topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(help_text="Подстрока URL для исключения (например, 'yandex.ru')", max_length=500, unique=True, verbose_name='Подстрока URL для исключения')),
                ('description', models.CharField(blank=True, help_text='Описание причины исключения', max_length=500, null=True, verbose_name='Описание причины исключения')),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли исключение', verbose_name='Активно ли исключение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Исключение URL',
                'verbose_name_plural': 'Исключения URL',
                'db_table': 'url_exclusions',
                'ordering': ['url_pattern'],
            },
        ),
        migrations.CreateModel(
            name='CrawledAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Найденный адрес', verbose_name='Найденный адрес')),
                ('address_cleaned', models.TextField(blank=True, help_text='Очищенная версия адреса', null=True, verbose_name='Очищенная версия адреса')),
                ('context', models.TextField(blank=True, help_text='Контекст вокруг адреса', null=True, verbose_name='Контекст вокруг адреса')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('crawled_data', models.ForeignKey(help_text='ID записи краулинга', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.crawleddata', verbose_name='Запись краулинга')),
            ],
            options={
                'verbose_name': 'Найденный адрес',
                'verbose_name_plural': 'Найденные адреса',
                'db_table': 'crawled_addresses',
                'ordering': ['crawled_data'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Заголовок результата', max_length=500, null=True, verbose_name='Заголовок результата')),
                ('url', models.TextField(help_text='URL страницы', verbose_name='URL страницы')),
                ('domain', models.CharField(blank=True, help_text='Домен', max_length=255, null=True, verbose_name='Домен')),
                ('snippet', models.TextField(blank=True, help_text='Сниппет из выдачи', null=True, verbose_name='Сниппет из выдачи')),
                ('position', models.IntegerField(blank=True, help_text='Позиция в выдаче', null=True, verbose_name='Позиция в выдаче')),
                ('processed', models.BooleanField(default=False, help_text='Флаг обработки (crawling)', verbose_name='Флаг обработки (crawling)')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Дата и время crawling-а', null=True, verbose_name='Дата и время crawling-а')),
                ('skipped', models.BooleanField(default=False, help_text='Был пропущен (исключение)', verbose_name='Был пропущен (исключение)')),
                ('skip_reason', models.CharField(blank=True, help_text='Причина пропуска', max_length=255, null=True, verbose_name='Причина пропуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи', verbose_name='Дата создания записи')),
                ('history', models.ForeignKey(help_text='ID записи истории поиска', on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='core.searchhistory', verbose_name='Запись истории поиска')),
            ],
            options={
                'verbose_name': 'Результат поиска',
                'verbose_name_plural': 'Результаты поиска',
                'db_table': 'search_results',
                'ordering': ['history', 'position'],
            },
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='search_result',
            field=models.OneToOneField(help_text='ID результата поиска', on_delete=django.db.models.deletion.CASCADE, related_name='crawled_data', to='core.searchresult', verbose_name='Результат поиска'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='topic',
            field=models.ForeignKey(help_text='ID темы поиска', on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to='core.searchtopic', verbose_name='Тема поиска'),
        ),
        migrations.CreateModel(
            name='CrawledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email адрес', max_length=255, verbose_name='Email адрес')),
                ('context', models.TextField(blank=True, help_text='Контекст вокруг email', null=True, verbose_name='Контекст вокруг email')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('crawled_data', models.ForeignKey(help_text='ID записи краулинга', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.crawleddata', verbose_name='Запись краулинга')),
            ],
            options={
                'verbose_name': 'Найденный email',
                'verbose_name_plural': 'Найденные email',
                'db_table': 'crawled_emails',
                'ordering': ['crawled_data'],
                'indexes': [models.Index(fields=['email'], name='crawled_ema_email_a547ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawledPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Номер телефона в формате +7XXXXXXXXXX', max_length=20, verbose_name='Номер телефона')),
                ('phone_raw', models.CharField(blank=True, help_text='Исходный текст с телефоном', max_length=100, null=True, verbose_name='Исходный текст с телефоном')),
                ('context', models.TextField(blank=True, help_text='Контекст вокруг телефона', null=True, verbose_name='Контекст вокруг телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('crawled_data', models.ForeignKey(help_text='ID записи краулинга', on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.crawleddata', verbose_name='Запись краулинга')),
            ],
            options={
                'verbose_name': 'Найденный телефон',
                'verbose_name_plural': 'Найденные телефоны',
                'db_table': 'crawled_phones',
                'ordering': ['crawled_data'],
                'indexes': [models.Index(fields=['phone'], name='crawled_pho_phone_67cb1b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['history', 'position'], name='search_resu_history_1692f2_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['url'], name='search_resu_url_96b841_idx'),
        ),
        migrations.AddIndex(
            model_name='crawleddata',
            index=models.Index(fields=['search_result'], name='crawled_dat_search__d47b32_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['topic', '-search_datetime'], name='search_hist_topic_i_947254_idx'),
        ),
    ]
