# Generated by Django 6.0.3 on 2026-03-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledemail',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Тема поиска, в рамках которой найден email', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawled_emails', to='core.searchtopic', verbose_name='Тема поиска'),
        ),
        migrations.AddField(
            model_name='crawledphone',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Тема поиска, в рамках которой найден телефон', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawled_phones', to='core.searchtopic', verbose_name='Тема поиска'),
        ),
        migrations.AddIndex(
            model_name='crawledemail',
            index=models.Index(fields=['topic', 'email'], name='crawled_ema_topic_i_d8b529_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledphone',
            index=models.Index(fields=['topic', 'phone'], name='crawled_pho_topic_i_bae3d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawledemail',
            constraint=models.UniqueConstraint(fields=('topic', 'email'), name='unique_email_per_topic'),
        ),
        migrations.AddConstraint(
            model_name='crawledphone',
            constraint=models.UniqueConstraint(fields=('topic', 'phone'), name='unique_phone_per_topic'),
        ),
    ]
