# Generated by Django 6.0.3 on 2026-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crawledemail_topic_crawledphone_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='page_size',
            field=models.IntegerField(default=50, help_text='Количество результатов на одной странице поисковой выдачи', verbose_name='Размер страницы выдачи'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='page',
            field=models.IntegerField(blank=True, help_text='Номер страницы поисковой выдачи (1, 2, 3...)', null=True, verbose_name='Номер страницы выдачи'),
        ),
    ]
