# Generated by Django 6.0.3 on 2026-03-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_searchhistory_page_size_searchresult_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawledaddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Найденный адрес', 'verbose_name_plural': 'Найденные адреса'},
        ),
        migrations.AlterModelOptions(
            name='crawledemail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Найденный email', 'verbose_name_plural': 'Найденные email'},
        ),
        migrations.AlterModelOptions(
            name='crawledphone',
            options={'ordering': ['-created_at'], 'verbose_name': 'Найденный телефон', 'verbose_name_plural': 'Найденные телефоны'},
        ),
        migrations.AddField(
            model_name='crawledaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата последнего обновления записи', verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='crawledemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата последнего обновления записи', verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='crawledphone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата последнего обновления записи', verbose_name='Дата последнего обновления'),
        ),
        migrations.AddIndex(
            model_name='crawledaddress',
            index=models.Index(fields=['updated_at'], name='crawled_add_updated_1c03d0_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledemail',
            index=models.Index(fields=['updated_at'], name='crawled_ema_updated_ca149e_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledphone',
            index=models.Index(fields=['updated_at'], name='crawled_pho_updated_93712b_idx'),
        ),
    ]
