# Generated by Django 6.0.3 on 2026-03-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_crawledaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledphone',
            name='first_seen_page',
            field=models.IntegerField(blank=True, help_text='Номер страницы поисковой выдачи, где телефон был найден впервые', null=True, verbose_name='Страница первого обнаружения'),
        ),
        migrations.AddField(
            model_name='crawledphone',
            name='last_seen_page',
            field=models.IntegerField(blank=True, help_text='Номер страницы поисковой выдачи, где телефон был найден последний раз', null=True, verbose_name='Страница последнего обнаружения'),
        ),
    ]
