# Generated by Django 6.0.3 on 2026-03-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crawledphone_first_seen_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledPhoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Номер телефона в формате +7XXXXXXXXXX', max_length=20, verbose_name='Номер телефона')),
                ('page', models.IntegerField(help_text='Номер страницы поисковой выдачи (1, 2, 3...)', verbose_name='Страница обнаружения')),
                ('position', models.IntegerField(blank=True, help_text='Позиция телефона на странице выдачи (опционально)', null=True, verbose_name='Позиция на странице')),
                ('search_date', models.DateTimeField(help_text='Дата и время, когда был выполнен поиск', verbose_name='Дата выдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи в БД', verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления записи', verbose_name='Дата последнего обновления')),
                ('topic', models.ForeignKey(help_text='Тема поиска, в рамках которой найден телефон', on_delete=django.db.models.deletion.CASCADE, related_name='phone_history', to='core.searchtopic', verbose_name='Тема поиска')),
            ],
            options={
                'verbose_name': 'История появления телефона',
                'verbose_name_plural': 'История появлений телефонов в поисковой выдаче',
                'db_table': 'crawled_phone_history',
                'ordering': ['-search_date', 'topic', 'phone', 'page'],
                'indexes': [models.Index(fields=['topic', 'phone'], name='crawled_pho_topic_i_6c785c_idx'), models.Index(fields=['search_date'], name='crawled_pho_search__ee36cc_idx'), models.Index(fields=['topic', 'search_date'], name='crawled_pho_topic_i_2664cd_idx'), models.Index(fields=['phone', 'search_date'], name='crawled_pho_phone_4d467b_idx'), models.Index(fields=['topic', 'page', 'search_date'], name='crawled_pho_topic_i_5f6dc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('topic', 'phone', 'search_date', 'page'), name='unique_phone_history_per_search')],
            },
        ),
    ]
