# Generated by Django 6.0.3 on 2026-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_crawledphonehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledphonehistory',
            name='search_date',
            field=models.DateField(help_text='Дата, когда был выполнен поиск', verbose_name='Дата выдачи'),
        ),
    ]
