# Generated by Django 6.0.3 on 2026-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_crawledphonehistory_search_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledphonehistory',
            name='url',
            field=models.TextField(blank=True, help_text='URL страницы', null=True, verbose_name='URL страницы'),
        ),
    ]
